### ISSUE TITLE
Is there a way to register a "shortkey" without an element?

### ISSUE THREAD

**Issue by AllanOricil** [fgr-araujo/vue-shortkey#124]
I could not find a way to register a shortkey without an element using this lib.

To achieve the desired result I had to use an eventListener.

````js
beforeMount(){
      window.addEventListener('keyup', (event) => {
        if(event.ctrlKey && event.key === 'f') this.onClickHideFormButton();
      })
},
destroyed(){
      window.removeEventListener('keyup');
}
````

 It would be good if you could expose a method from your API to be used from the js. Like,

````js
ìmport { mapShortKey } from 'vue-shortkey';
created(){
      mapShortKey(['ctrl', 'f'], () => {
        this.doSomething():
      })
}
````

**Comment by iFgR** [comment]
This can be interesting

**Comment by sudofox** [comment]
I need to be able to register and destroy shortkeys within a sub-component in my app _as well as_ temporarily disable shortkeys used by the main component since I'm working on a social site with a painting app built in.

But yeah, a lot of things don't have buttons tied to them that would be useful to register/destroy
